[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_marketplace = "mktYdagPAAnuHigRD62zLpHshZqx7vpKHjN3fN6MPjy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ivmidable/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
